export declare const lightTheme: {
    body: string;
    text: string;
    primary: string;
    secondary: string;
    background: string;
    primaryText: string;
    inputBackground: string;
    inputText: string;
    toggleBackground: string;
    iconColor: string;
    headerBackground: string;
    hoverBackground: string;
    bodyBackground: string;
    bodyText: string;
    cardBackground: string;
    readButtonBackground: string;
    writeButtonBackground: string;
    readButtonHover: string;
    writeButtonHover: string;
};
export declare const darkTheme: {
    body: string;
    text: string;
    primary: string;
    secondary: string;
    background: string;
    primaryText: string;
    inputBackground: string;
    inputText: string;
    toggleBackground: string;
    iconColor: string;
    headerBackground: string;
    hoverBackground: string;
    bodyBackground: string;
    bodyText: string;
    cardBackground: string;
    readButtonBackground: string;
    writeButtonBackground: string;
    readButtonHover: string;
    writeButtonHover: string;
};
